on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: search-engines-urls-push
    steps:
      - name: search-engines-urls-push
        id: search-engines-urls-push
        uses: 3Alan/search-engines-urls-push@v0.1.0
        with:
          site: 'https://www.alanwang.site/'
          sitemap: 'https://www.alanwang.site/sitemap.xml'
          count: ${{ secrets.COUNT }}
          bing-token: ${{ secrets.BING_TOKEN }}
          baidu-token: ${{ secrets.BAIDU_TOKEN }}
          google-client-email: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          google-private-key: ${{ secrets.GOOGLE_PRIVATE_KEY }}
